#pragma once

#define BOARD_WIDTH 20
#define BOARD_HEIGHT 20

#define ARROWUP 0x48
#define ARROWDOWN 0x50
#define ARROWLEFT 0x4b
#define ARROWRIGHT 0x4d
#define ESCAPE 27
#define ENTER 0x0d

#define INICJATYWA_CZLOWIEKA 4
#define SILA_CZLOWIEKA 5
#define SYMBOL_CZLOWIEKA 'C'

#define INICJATYWA_WILKA 5
#define SILA_WILKA 9
#define SYMBOL_WILKA 'W'

#define INICJATYWA_OWCY 4
#define SILA_OWCY 4
#define SYMBOL_OWCY 'O'

#define INICJATYWA_LISA 7
#define SILA_LISA 3
#define SYMBOL_LISA 'L'

#define INICJATYWA_ZOLWIA 1
#define SILA_ZOLWIA 2
#define SYMBOL_ZOLWIA 'Z'

#define INICJATYWA_ANTYLOPY 4
#define SILA_ANTYLOPY 4
#define SYMBOL_ANTYLOPY 'A'

#define SYMBOL_TRAWY 't'

#define SYMBOL_MLECZA 'm'

#define SYMBOL_GUARANY 'g'

#define SYMBOL_WILCZEJJAGODY 'j'
#define SILA_WILECZEJJAGODY 99

#define SYMBOL_BARSZCZU 'b'
#define SILA_BARSZCZU 10
